#!/bin/sh
## xdg-open -- opens shit

URI="$*"

# yank the URI first
printf '%s' "$URI" | xsel -i

case $URI in
    # images
	*png|*jpg|*jpe|*jpeg|*gif)
		feh "$1" >/dev/null 2>&1 & ;;
    *.gif) mpv "$URI" ;;
    
    # video
	*mkv|*webm|*mp4|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*)
		mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 & ;;

    # audio
	*mp3|*flac|*opus|*mp3?source*)
		mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) --quiet "$1" >/dev/null 2>&1 & ;;

    # documents
    *.txt) 
        alacritty -e sh -c "curl -s '$URI' | less" >/dev/null 2>&1 & ;;
    magnet:*) 
        alacritty -e "qbittorrent "$URI"" >/dev/null 2>&1 & ;;
    *.pdf) 
        curl -s "$URI" -o /tmp/doc.pdf; zathura /tmp/doc.pdf 2>&1 & ;;

    # other
    *) qutebrowser "$URI" 2>&1 & ;;
esac

